/**
 * X11 keysym name → Unicode glyph.
 * Latin-1 keysyms use the keysym value. Others use the U+ comment in
 * `keysymdef.h`. `Cyrillic_SHCH` is the truncated capital in the LARK
 * `ru` legacy section; the real keysym is `Cyrillic_SHCHA`.
 */
export const KEYSYM_GLYPHS: Readonly<Record<string, string>> = {
  A: 'A',
  B: 'B',
  C: 'C',
  Cyrillic_A: 'А',
  Cyrillic_BE: 'Б',
  Cyrillic_CHE: 'Ч',
  Cyrillic_DE: 'Д',
  Cyrillic_E: 'Э',
  Cyrillic_EF: 'Ф',
  Cyrillic_EL: 'Л',
  Cyrillic_EM: 'М',
  Cyrillic_EN: 'Н',
  Cyrillic_ER: 'Р',
  Cyrillic_ES: 'С',
  Cyrillic_GHE: 'Г',
  Cyrillic_HA: 'Х',
  Cyrillic_HARDSIGN: 'Ъ',
  Cyrillic_I: 'И',
  Cyrillic_IE: 'Е',
  Cyrillic_IO: 'Ё',
  Cyrillic_KA: 'К',
  Cyrillic_O: 'О',
  Cyrillic_PE: 'П',
  Cyrillic_SHA: 'Ш',
  Cyrillic_SHORTI: 'Й',
  Cyrillic_SOFTSIGN: 'Ь',
  Cyrillic_TE: 'Т',
  Cyrillic_TSE: 'Ц',
  Cyrillic_U: 'У',
  Cyrillic_VE: 'В',
  Cyrillic_YA: 'Я',
  Cyrillic_YERU: 'Ы',
  Cyrillic_YU: 'Ю',
  Cyrillic_ZE: 'З',
  Cyrillic_ZHE: 'Ж',
  Cyrillic_a: 'а',
  Cyrillic_be: 'б',
  Cyrillic_che: 'ч',
  Cyrillic_de: 'д',
  Cyrillic_e: 'э',
  Cyrillic_ef: 'ф',
  Cyrillic_el: 'л',
  Cyrillic_em: 'м',
  Cyrillic_en: 'н',
  Cyrillic_er: 'р',
  Cyrillic_es: 'с',
  Cyrillic_ghe: 'г',
  Cyrillic_ha: 'х',
  Cyrillic_hardsign: 'ъ',
  Cyrillic_i: 'и',
  Cyrillic_ie: 'е',
  Cyrillic_io: 'ё',
  Cyrillic_ka: 'к',
  Cyrillic_o: 'о',
  Cyrillic_pe: 'п',
  Cyrillic_sha: 'ш',
  Cyrillic_shcha: 'щ',
  Cyrillic_shorti: 'й',
  Cyrillic_softsign: 'ь',
  Cyrillic_te: 'т',
  Cyrillic_tse: 'ц',
  Cyrillic_u: 'у',
  Cyrillic_ve: 'в',
  Cyrillic_ya: 'я',
  Cyrillic_yeru: 'ы',
  Cyrillic_yu: 'ю',
  Cyrillic_ze: 'з',
  Cyrillic_zhe: 'ж',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  Greek_DELTA: 'Δ',
  Greek_OMEGA: 'Ω',
  Greek_PSI: 'Ψ',
  Greek_SIGMA: 'Σ',
  Greek_THETA: 'Θ',
  Greek_alpha: 'α',
  Greek_beta: 'β',
  Greek_chi: 'χ',
  Greek_delta: 'δ',
  Greek_epsilon: 'ε',
  Greek_eta: 'η',
  Greek_finalsmallsigma: 'ς',
  Greek_gamma: 'γ',
  Greek_iota: 'ι',
  Greek_lambda: 'λ',
  Greek_mu: 'μ',
  Greek_nu: 'ν',
  Greek_omega: 'ω',
  Greek_phi: 'φ',
  Greek_pi: 'π',
  Greek_psi: 'ψ',
  Greek_rho: 'ρ',
  Greek_sigma: 'σ',
  Greek_tau: 'τ',
  Greek_theta: 'θ',
  Greek_upsilon: 'υ',
  Greek_xi: 'ξ',
  Greek_zeta: 'ζ',
  H: 'H',
  I: 'I',
  J: 'J',
  K: 'K',
  L: 'L',
  M: 'M',
  N: 'N',
  O: 'O',
  Ooblique: 'Ø',
  P: 'P',
  Q: 'Q',
  R: 'R',
  S: 'S',
  T: 'T',
  U: 'U',
  V: 'V',
  W: 'W',
  X: 'X',
  Y: 'Y',
  Z: 'Z',
  a: 'a',
  ampersand: '&',
  apostrophe: "'",
  asciicircum: '^',
  asciitilde: '~',
  asterisk: '*',
  at: '@',
  b: 'b',
  backslash: '\\',
  bar: '|',
  braceleft: '{',
  braceright: '}',
  bracketleft: '[',
  bracketright: ']',
  c: 'c',
  colon: ':',
  comma: ',',
  d: 'd',
  degree: '°',
  dollar: '$',
  e: 'e',
  equal: '=',
  exclam: '!',
  f: 'f',
  g: 'g',
  grave: '`',
  greater: '>',
  greaterthanequal: '≥',
  guillemotleft: '«',
  guillemotright: '»',
  h: 'h',
  i: 'i',
  j: 'j',
  k: 'k',
  l: 'l',
  less: '<',
  lessthanequal: '≤',
  m: 'm',
  minus: '-',
  multiply: '×',
  n: 'n',
  notequal: '≠',
  numbersign: '#',
  numerosign: '№',
  o: 'o',
  oslash: 'ø',
  p: 'p',
  parenleft: '(',
  parenright: ')',
  percent: '%',
  period: '.',
  plusminus: '±',
  q: 'q',
  question: '?',
  quotedbl: '"',
  r: 'r',
  s: 's',
  semicolon: ';',
  slash: '/',
  t: 't',
  threesuperior: '³',
  twosuperior: '²',
  u: 'u',
  underscore: '_',
  v: 'v',
  w: 'w',
  x: 'x',
  y: 'y',
  z: 'z',
  Cyrillic_SHCH: '\u0429',
}

const NON_CHARACTER = new Set(['Multi_key', 'ISO_Level3_Shift', 'ISO_Level5_Shift'])

/**
 * Character produced by a keysym name.
 * `NoSymbol` is an empty string. Modifier keysyms (`Multi_key`) are null.
 */
export function keysymToGlyph(name: string): string | null {
  if (name === 'NoSymbol' || name === 'VoidSymbol') return ''
  const named = KEYSYM_GLYPHS[name]
  if (named) return named
  if (/^U[0-9A-Fa-f]{4,6}$/.test(name)) {
    return String.fromCodePoint(Number.parseInt(name.slice(1), 16))
  }
  if (/^0x[0-9A-Fa-f]+$/.test(name)) {
    const value = Number.parseInt(name, 16)
    if ((value & 0xff000000) === 0x01000000) return String.fromCodePoint(value & 0x00ffffff)
    if ((value >= 0x20 && value <= 0x7e) || (value >= 0xa0 && value <= 0xff)) {
      return String.fromCodePoint(value)
    }
  }
  if (name.length === 1) return name
  if (NON_CHARACTER.has(name)) return null
  return null
}
